# Generated by Django 5.0.6 on 2024-06-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_02', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(default=123456),
            preserve_default=False,
        ),
    ]
