# Generated by Django 5.0.6 on 2024-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_02', '0005_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
